entur:
  jwt:
    enabled: true
    claims:
      expires-at-leeway: 15
      issued-at-leeway: 5
      audiences:
        - https://my.audience
    mdc:
      enabled: true
      mappings:
      - from: iss
        to: issuer
      - from: azp
        to: azp
    jwk:
      health-indicator:
        enabled: true
    authorization:
      permit-all:
        mvc-matcher:
          patterns:
           - /actuator/health
           - /unprotected
  cors:
    enabled: true
    mode: api
    origins:
    - https://my.published.api
